### PR TITLE
Simple pattern

### PR DESCRIPTION
**Pull request by PanDoreS**
Hi,
I've just discovered LX Studio and created this pattern by learning the API. Even if it's super basic compared to the rest of the other pattern, I found kind of artistic so you may be interested to include it in your project 😃 
If the arguments are incorrect, don't hesitate to tell me ;)

Cheers !

### CODE REVIEW

**Comment by Geethree** [comment]
Hey @PanDoreS, 

Please run `./gradlew spotlessApply` on your code to format it and re push.

Also, how did you find us? Where did you come from? Are you connected to the temple? The answers don't matter, we are just curious. =)

**Comment by PanDoreS** [comment]
Hi,
It's done ! I'm still learning this, my bad 😄 
I have a friend that volunteer on some shifts over the last few weeks in SF. He, with another friend, will attempt this year Burning Man. He shared the post on the Galaxia page about the opportunity to create the light pattern for the 2018 temple and it might interest me (it did 😛).
I'm a software engineer in Paris, a long way from you guys haha! I won't see this temple from my own eyes but I'm glad to help !

**Comment by Geethree** [comment]
Neat! benoit?

OK. This is awesome. I'd suggest that you add some movement to it! Checkout the [modulators in the lx docs](http://lx.studio/api/heronarts/lx/modulator/package-frame.html).

Maybe instead of one of your bounded parameters, add a sawlfo then use the parameter to modify the speed?

**Comment by PanDoreS** [comment]
Haha no, my friend is Jean 😜
Thanks for your suggestion, I’ll work on it tonight !

**Comment by PanDoreS** [comment]
Hi Gerald,
I've added the modulator on my main pattern and fixed some ugly stuff 😛 
I've also tried new modulators on new patterns to train myself.

Don't hesitate to give me some feedback on it ;) I'll keep having fun over this week end to try new stuff

Have a nice day

**Comment by Geethree** [comment]
Needs a master merge =)

**Comment by Geethree** [comment]
These are great. A little fast thought. Lets get some default speeds that are on the order of heart beats in frequency. We need to ensure that the blinky blinks aren't distracting. Checkout swirl for a good reference of speed.

**Comment by PanDoreS** [comment]
Thanks !
Okay, I’ll modify the speed on all of them tonight 😉

Cheers

**Comment by PanDoreS** [comment]
Hello Gerald,
I've modified the default speeds like you've requested, tell me if everything is good for you 😉 
I've also modified the range of them to reflect the overall speed.

Thanks, and have a nice week-end 😃

**Comment by Geethree** [comment]
=D

image

**Comment by Geethree** [comment]
I like it. @deleted Would you give this a look over?

**Comment by meawoppl** [comment]
Heyo, @PanDoreS I am going to get all these new patterns merged tonight, can you process the conflict?  Looks small

**Comment by PanDoreS** [comment]
Oh sure ! It’ll be done in 4 hours top 😉

**Comment by PanDoreS** [comment]
Hi ! It should be good to go now.
Don't hesitate to tell me if something is wrong 😄 

Cheers !

**Review by deleted — APPROVED** [review]
LGTM! I'm merging.

**Comment by PanDoreS** [comment]
Awesome 😃 
Have a nice day

**Pull request merged**
