### PR TITLE
Three patterns by Alan Persak

### PR DESCRIPTION
**Pull request by alanpersak**
This change adds three new patterns:

MessagePattern: messages as binary waveforms that travel up the petals.
StarPattern: randomized stars that fade in and out.
WavePattern: randomized waves that expand outward from the center.

Please see the source docs for details.

Cheers,
Alan

### CODE REVIEW

**Comment by deleted** [comment]
@alanpersak Thanks for submitting patterns!

I haven't reviewed these yet, but I notice that both you and @antonjs have written patterns that encode and display meaningful string messages. (His is [Morse encoding](https://github.com/temple2018/Galaxia/pull/29), yours is ASCII). Perhaps the two of you would like to coordinate on how to get input strings.

**Comment by alanpersak** [comment]
Thanks Tedward!

I'll send him an email and we can coordinate on that. My thought was to use
a google survey or something similar. that would make it easy to dump
submissions to a csv file which the animation could load from.

Btw, we met at priceless. I'm the dork who talked with you about star trek
after rachel lark's set.

Cheers,
Alan

**Comment by deleted** [comment]
Oh yeah! I remember you.
Hello & thanks for submitting patterns.
I really like the stars one quite a lot.

**Review by deleted — APPROVED** [review]

**Comment by deleted** [comment]
@alanpersak I've approved this, but you'll need to run `./gradlew spotlessApply` to apply auto-formatting before it will bass CI. After you've done that and pushed, wait for CI to run and you should be able to merge it yourself. I tested this in #33 , but I'm unable to merge it without another reviewer, so I'll close that PR.

LMK if you encounter any further problems.

**Comment by alanpersak** [comment]
Sounds good, i'll take care of that tonight.

**Comment by deleted** [comment]
Awesome. Thanks Alan.

**Comment by alanpersak** [comment]
should be good to merge now!

**Pull request merged**
